### ISSUE TITLE
Encounter summary formatting

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#77]
When viewing a past encounter or previewing a current encounter, it seems like there is always a large gap of blank white space beneath the "Assessment" section, between the Diagnosis Code and the "Additional Diagnoses" subsection.

This large blank white space prevents viewing efficiency and requires more scrolling, and I was wondering if it would be possible to format these views so that the space did not exist.

**Comment by shihjay2** [comment]
Fixed in commit 14ddf903b7ecb4c2ef8925e66a24e875e2318180

**Comment by rumsant** [comment]
That seems to have fixed it everywhere except for the timeline of encounters you see when you click a patient's name at the top of the left sidebar. It appears that the blank space is still present  when viewing the patient encounter timeline.

**Comment by shihjay2** [comment]
Thanks, fixed in commit 318215dc75336f4103ae469b1b76b52de6da95ff
